#
#  Author: Nho Luong
#  Date: 2021-10-28 14:46:04 +0100 (Thu, 23 Oct 2021)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/nholuongut/kubernetes-configs
#
#  License: see accompanying Nho Luong LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn
#  and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/nholuong
#

# ============================================================================ #
#                           B u i l d K i t e   H P A
# ============================================================================ #

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: buildkite-agent
  namespace: buildkite
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: buildkite-agent
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
